version: '3'
services:
  web:
    build: .
    environment:
      - SECRET_KEY_BASE=1
      - RAILS_ENV=development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
